[default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
anvil = "http://localhost:8545"

[profile.default]
# Configuraci칩n para scripts de despliegue
sender = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"  # Primera cuenta de Anvil
# Optimizaciones agresivas para reducir el tama침o del contrato
optimizer = true
optimizer_runs = 10000  # M치s optimizaciones = menor tama침o de bytecode
via_ir = false
